### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by Cyral** [Pyratron/Bricklayer#11]
Implement world minimap using an array of colors to create a texture.

Question: How should we handle large worlds where the minimap will be too big for the screen (or too big to be a reasonable size?)

**Comment by Cyral** [comment]
I was thinking we could show a small section of the minimap if the world is too large, and limit the minimap size.

**Comment by Pugmatt** [comment]
Maybe if the player clicks on the minimap, the position of the view can be moved around with the mouse. Or the option to expand the minimap.
