### ISSUE TITLE
Can't join rooms that are closed.

### ISSUE THREAD

**Issue by Cyral** [Pyratron/Bricklayer#8]
Fix joining rooms when they are closed.

**Comment by Cyral** [comment]
This is caused because rooms are only saved when all users leave them, simply ending the debugging session will not save any worlds. (however they will be inserted into the DB).

Possible solution is to save the world once generating. If this ever becomes a performance problem, we can look into it.

Eventually an auto save feature needs to be added also. (Maybe for debug builds we could save the room every minute or so, as most debugging sessions aren't very long).

**Comment by ferk6a** [comment]
I agree with just saving the world when generating, it's what a normal game would appeal to. Auto-save or manual saving will probably have to be an option, but for now, well we have options. It would appeal more to me to having a simple save button or a char command for now.
